# Generated by Django 3.0.2 on 2020-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialist_in', models.CharField(max_length=50)),
                ('doctor_gender', models.CharField(max_length=50)),
                ('doctor_locality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=8)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(max_length=50)),
                ('patient_disease', models.CharField(max_length=50)),
                ('patient_mob_num', models.CharField(max_length=12)),
                ('patient_mail', models.EmailField(max_length=50)),
                ('patient_locality', models.CharField(max_length=50)),
                ('visting_doctor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
