# Generated by Django 3.0.2 on 2020-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbmdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialist_in', models.CharField(max_length=50)),
                ('doctor_gender', models.CharField(max_length=50)),
                ('doctor_mobile_number', models.CharField(max_length=12)),
                ('doctor_locality', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='patients',
            new_name='Patient',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
